/* jev-ultrafast-mcp — in-page observer + guarded execution support.
 *
 * Installed on the TOP-LEVEL window only (same-origin frames reach it through
 * window.top). Responsibilities:
 *
 *   1. readState()   — one atomic read of visible text + actionable elements,
 *                      each with a code-owned, observation-stable ref.
 *   2. verify()      — strict freshness: still the page and element observed?
 *   3. reinspect()   — relaxed freshness: still the same control? Used for the
 *                      second and later ops of a batch, where earlier ops have
 *                      legitimately mutated the page.
 *   4. resolve()     — geometry + occlusion, recomputed just before input.
 *
 * Design rules (carried over from browser-use/jev-ultrafast):
 *   - Refs are owned by code, never generated by a model.
 *   - Geometry is always re-resolved immediately before input.
 *   - Page text is untrusted data, never instructions.
 */
(() => {
  const W = window;
  // Which helper this is. One declaration, because two copies of a version
  // number are two versions waiting to disagree: the guard below and the value
  // this file reports have to be the same fact, and `browser.HELPER_VERSION`
  // has to match both. It was three separate literals, and the server's had
  // been bumped while these two had not -- so the check could never be
  // satisfied, the server re-injected this whole file on every observation, and
  // a page holding the older helper was never actually upgraded, because the
  // early return fired on the number it already carried.
  const VERSION = 10;
  try { if (W !== W.top) return; } catch (_) { return; }
  if (W.__jevMcp && W.__jevMcp.version === VERSION) return;

  // Refs survive a helper re-injection, so an agent can keep referring to e37
  // across observes. `next` is monotonic: a pruned ref is never recycled.
  const S = W.__jevRefs || (W.__jevRefs = { ids: new WeakMap(), nodes: new Map(), next: 1, snap: null });

  const ROLES = ['button', 'link', 'checkbox', 'radio', 'switch', 'tab', 'menuitem',
    'menuitemcheckbox', 'menuitemradio', 'option', 'treeitem', 'gridcell', 'combobox',
    'textbox', 'searchbox', 'spinbutton', 'listbox'];
  const SELECTOR = 'a[href],button,input,textarea,select,summary,[contenteditable=""],' +
    '[contenteditable="true"],' + ROLES.map(r => '[role="' + r + '"]').join(',');
  const UNSAFE_TYPES = ['hidden'];

  // Word-bounded on purpose: /pass/ alone flags "Passengers", /code/ alone
  // flags every "Promo code" field -- and `safety.is_secret` on the server side
  // matches the same names, because the observation masks on the union of this flag
  // and that list. A name only this side matches is a field whose value the agent
  // cannot read.
  const SECRET_HINT = new RegExp([
    '\\bpassword\\b', '\\bpasswd\\b', '\\bpasscode\\b', '\\bpassphrase\\b',
    '\\botp\\b', '\\bone[- ]?time\\b', '\\bverification code\\b', '\\bsecurity code\\b',
    '\\bcvv\\b', '\\bcvc\\b', '\\bcard\\s*number\\b', '\\bsecret\\b',
    '\\bapi\\s*key\\b', '\\baccess\\s*token\\b', '\\bssn\\b', '\\bsocial security\\b',
    '\\biban\\b', '\\brouting\\s*number\\b', '\\bsecurity\\s*answer\\b', '\\bpin\\b',
  ].join('|'), 'i');

  const PRIMARY = new Set(['button', 'combobox', 'listbox', 'textbox', 'searchbox',
    'checkbox', 'radio', 'switch', 'spinbutton', 'file', 'listbox']);
  const SECONDARY = new Set(['option', 'tab', 'menuitem', 'menuitemcheckbox',
    'menuitemradio', 'treeitem', 'gridcell', 'radio', 'checkbox', 'switch']);

  /* ---------------------------------------------------------------- helpers */

  const clean = s => (s || '').replace(/\s+/g, ' ').trim();

  const identity = e => {
    if (!S.ids.has(e)) { S.ids.set(e, S.next++); S.nodes.set(S.ids.get(e), e); }
    return S.ids.get(e);
  };

  const prune = () => { for (const [id, e] of S.nodes) if (!e.isConnected) S.nodes.delete(id); };

  // The input's *effective* type, which is what the browser renders and edits. The raw attribute
  // is not: HTML's default is `text`, so `<input name="q">`, `type=""` and an unrecognised type
  // are all text boxes, and reading the attribute left them with no role -- never editable, never
  // offered to TYPE_TEXT. `.type` is already lower-cased and resolved by the browser. Non-inputs
  // (a `<button type=submit>`, a `<ul>` with a stray attribute) keep reading the attribute.
  const typeOf = e => {
    if (e && e.tagName === 'INPUT' && typeof e.type === 'string') return e.type.toLowerCase();
    return ((e.getAttribute && e.getAttribute('type')) || '').toLowerCase();
  };
  const isFile = e => e.tagName === 'INPUT' && typeOf(e) === 'file';
  // Secret if *either* reading says password. `.type` is what the browser edits, but it is a
  // getter a page can override; the attribute is what the markup declared. Masking on the union
  // means neither one alone can un-mask a password field.
  const isPassword = e => typeOf(e) === 'password'
    || ((e.getAttribute && e.getAttribute('type')) || '').toLowerCase() === 'password';

  const deepVisible = e => {
    let n = e;
    while (n && n.nodeType === 1) {
      if (n.closest && n.closest('[aria-hidden="true"],[inert]')) return false;
      try { if (!n.checkVisibility({ checkOpacity: true, checkVisibilityCSS: true })) return false; } catch (_) { return false; }
      if (n.parentElement) { n = n.parentElement; continue; }
      const root = n.getRootNode && n.getRootNode();
      n = root && root instanceof ShadowRoot ? root.host : null;
    }
    return true;
  };

  // `document.elementFromPoint` stops at a shadow host, so a control inside a
  // web component looks permanently "covered". Descend the shadow tree.
  const deepElementFromPoint = (doc, x, y) => {
    let element = doc.elementFromPoint(x, y);
    let guard = 0;
    while (element && element.shadowRoot && guard++ < 12) {
      const inner = element.shadowRoot.elementFromPoint(x, y);
      if (!inner || inner === element) break;
      element = inner;
    }
    return element;
  };

  const roleOf = e => {
    const explicit = e.getAttribute('role');
    if (explicit && ROLES.includes(explicit)) return explicit;
    const tag = e.tagName;
    if (tag === 'BUTTON' || tag === 'SUMMARY') return 'button';
    if (tag === 'A') return 'link';
    if (tag === 'SELECT') return e.multiple ? 'listbox' : 'combobox';
    if (tag === 'TEXTAREA' || e.isContentEditable) return 'textbox';
    if (tag === 'INPUT') {
      const t = typeOf(e);
      if (t === 'checkbox') return 'checkbox';
      if (t === 'radio') return 'radio';
      if (['button', 'submit', 'reset', 'image'].includes(t)) return 'button';
      if (t === 'search') return 'searchbox';
      if (t === 'number') return 'spinbutton';
      if (t === 'file') return 'file';
      if (['text', 'email', 'url', 'tel', 'date', 'datetime-local', 'month',
        'week', 'time', 'password'].includes(t)) return 'textbox';
    }
    return null;
  };

  const FLAT = ['button', 'submit', 'reset', 'image'];

  const nameOf = (e, seen) => {
    seen = seen || new Set();
    if (!e || seen.has(e)) return '';
    seen.add(e);
    const byId = (e.getAttribute('aria-labelledby') || '').split(/\s+/)
      .map(id => nameOf(document.getElementById(id), seen)).filter(Boolean).join(' ');
    if (byId) return byId;
    const label = e.getAttribute('aria-label');
    if (label) return label;
    if (e.labels && e.labels.length) {
      const fromLabel = [...e.labels].map(l => nameOf(l, seen)).filter(Boolean).join(' ');
      if (fromLabel) return fromLabel;
    }
    if (FLAT.includes(typeOf(e)) && e.value) return e.value;
    if (e.getAttribute('alt')) return e.getAttribute('alt');
    if (e.tagName !== 'INPUT' && e.tagName !== 'TEXTAREA') {
      const fromText = [...e.childNodes].map(n => n.nodeType === 3 ? n.textContent
        : n.nodeType === 1 && n.getAttribute('aria-hidden') !== 'true' ? nameOf(n, seen) : '').join(' ').trim();
      if (fromText) return fromText;
    }
    return e.getAttribute('title') || e.getAttribute('placeholder') || '';
  };

  const valueOf = e => {
    if (isFile(e)) return e.files && e.files.length ? [...e.files].map(f => f.name).join(', ') : '';
    if ('value' in e && !['checkbox', 'radio'].includes(typeOf(e))) return String(e.value == null ? '' : e.value);
    if (e.isContentEditable) return clean(e.innerText);
    if (roleOf(e) === 'combobox' && e.tagName !== 'SELECT') return clean(e.innerText);
    return '';
  };

  const disabled = e => e.matches(':disabled') || !!e.closest('[aria-disabled="true"],[inert]');

  const isEditable = e => {
    if (isFile(e) || e.tagName === 'SELECT') return false;
    const role = roleOf(e);
    if (!['textbox', 'searchbox', 'spinbutton', 'combobox'].includes(role)) return false;
    if (role === 'combobox' && !['INPUT', 'TEXTAREA'].includes(e.tagName)) return false;
    if (e.readOnly || e.getAttribute('aria-readonly') === 'true') return false;
    if (disabled(e)) return false;
    return true;
  };

  /* ------------------------------------------------------- frame traversal */

  const frameChainOf = e => {
    const chain = [];
    let view = e.ownerDocument && e.ownerDocument.defaultView;
    let guard = 0;
    while (view && view !== W && guard++ < 12) {
      let fe = null;
      try { fe = view.frameElement; } catch (_) { fe = null; }
      if (!fe) break;
      chain.unshift(fe);
      try { view = fe.ownerDocument.defaultView; } catch (_) { break; }
    }
    return chain;
  };

  // Cheap offset: geometry only, no hit test. Used for ranking.
  const frameOffset = chain => {
    let x = 0, y = 0;
    for (const f of chain) {
      if (!f.isConnected || !deepVisible(f)) return null;
      const r = f.getBoundingClientRect();
      x += r.x; y += r.y;
    }
    return { x, y };
  };

  // Strict offset: also proves every frame in the chain is actually hit-testable.
  const offsetFor = chain => {
    let x = 0, y = 0;
    for (const f of chain) {
      if (!f.isConnected || !deepVisible(f)) return { ok: false, reason: 'frame_hidden' };
      const r = f.getBoundingClientRect();
      const doc = f.ownerDocument, view = doc.defaultView;
      const hx = r.x + r.width / 2, hy = r.y + r.height / 2;
      if (hx < 0 || hy < 0 || hx >= view.innerWidth || hy >= view.innerHeight) {
        return { ok: false, reason: 'frame_out_of_viewport' };
      }
      const hit = deepElementFromPoint(doc, hx, hy);
      if (!hit || !(hit === f || f.contains(hit))) return { ok: false, reason: 'frame_occluded' };
      x += r.x; y += r.y;
    }
    return { ok: true, x, y };
  };

  const rootList = () => {
    const out = [];
    const cross = [];
    const visit = (doc, chain, depth) => {
      if (depth > 6) return;
      out.push({ doc, chain });
      let frames = [];
      try { frames = doc.querySelectorAll('iframe,frame'); } catch (_) { return; }
      for (const f of frames) {
        let cd = null;
        try { cd = f.contentDocument; } catch (_) { cd = null; }
        if (cd && cd.body) visit(cd, chain.concat([f]), depth + 1);
        else cross.push({ chain: chain.concat([f]), src: f.getAttribute('src') || '' });
      }
    };
    visit(document, [], 0);
    return { roots: out, cross };
  };

  const rootsOf = root => {
    const out = [root];
    let all = [];
    try { all = root.querySelectorAll('*'); } catch (_) { return out; }
    if (all.length > 20000) return out;
    for (const e of all) if (e.shadowRoot) out.push(...rootsOf(e.shadowRoot));
    return out;
  };

  /* ------------------------------------------------------------ page state */

  const pageFields = () => [...document.querySelectorAll('input,textarea,select')]
    .filter(e => !UNSAFE_TYPES.includes(typeOf(e)))
    .map(e => [identity(e), valueOf(e), !!e.checked, e.selectedIndex, e.disabled, e.readOnly]);

  // Scroll is deliberately excluded: geometry is re-resolved before every
  // input anyway, so a scroll (ours or the page's) is not a semantic change
  // and must not invalidate a decision. Form values are included, because
  // those genuinely change what a ref means.
  const keyOf = () => JSON.stringify([performance.timeOrigin, location.href,
    innerWidth, innerHeight, pageFields()]);

  const scopeOf = e => e.closest('form,dialog,[role="dialog"],article,li,tr,[role="row"],[role="listitem"]') || e.parentElement;

  const guardOf = e => {
    if (!e || !e.isConnected || !deepVisible(e)) return null;
    const scope = scopeOf(e);
    return JSON.stringify([identity(e), roleOf(e), nameOf(e), valueOf(e),
      typeOf(e) && ['checkbox', 'radio'].includes(typeOf(e)) ? !!e.checked : null,
      e.selectedIndex == null ? null : e.selectedIndex, !!e.readOnly, disabled(e),
      e.getAttribute('aria-disabled'), e.getAttribute('aria-expanded'),
      e.getAttribute('aria-checked'), e.getAttribute('aria-selected'), e.getAttribute('href'),
      scope ? clean(scope.innerText).slice(0, 400) : '']);
  };

  const textOf = max => {
    const words = [];
    const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
    const range = document.createRange();
    let node, length = 0;
    while ((node = walker.nextNode()) && length < max) {
      const value = clean(node.textContent), parent = node.parentElement;
      if (!value || !parent || parent.closest('script,style,noscript,template')) continue;
      if (!deepVisible(parent)) continue;
      range.selectNodeContents(node);
      const r = range.getBoundingClientRect();
      if (r.width > 0 && r.height > 0 && r.bottom > 0 && r.top < innerHeight && r.right > 0 && r.left < innerWidth) {
        words.push(value); length += value.length;
      }
    }
    return words.join('\n').slice(0, max);
  };

  const overlays = () => [...document.querySelectorAll('dialog[open],[role="dialog"],[role="alertdialog"],[aria-modal="true"]')]
    .filter(e => deepVisible(e))
    .slice(0, 3)
    .map(e => ({
      role: e.getAttribute('role') || 'dialog',
      name: clean(nameOf(e)).slice(0, 80),
      modal: e.getAttribute('aria-modal') === 'true' || e.tagName === 'DIALOG',
    }));

  /* ------------------------------------------------------------ readState */

  const readState = opts => {
    opts = opts || {};
    const maxActions = opts.maxActions || 250;
    const maxText = opts.maxText || 6000;
    prune();
    const { roots, cross } = rootList();
    const height = document.documentElement.scrollHeight;

    const items = [];
    const seen = new Set();
    for (const { doc, chain } of roots) {
      for (const root of rootsOf(doc)) {
        let found = [];
        try { found = root.querySelectorAll(SELECTOR); } catch (_) { continue; }
        for (const e of found) {
          if (seen.has(e)) continue;
          if (UNSAFE_TYPES.includes(typeOf(e))) continue;
          // Disabled controls are kept rather than dropped. A control that
          // exists and cannot be used is information the model needs: a submit
          // button that only enables once an option is chosen is the ordinary
          // shape of a form, and dropping it silently is how the model ends up
          // able to select an option and with nothing to submit. `resolve`
          // already refuses one with reason 'disabled', so keeping it costs a
          // clear refusal rather than a wrong click.
          if (!e.isConnected || !deepVisible(e)) continue;
          const role = roleOf(e);
          if (!role) continue;
          if (role === 'gridcell' && e.querySelector('button,[role="button"]')) continue;
          const r = e.getBoundingClientRect();
          if (!r.width || !r.height) continue;
          seen.add(e);
          items.push({ e, role, chain, r });
        }
        if (items.length > maxActions * 6) break;
      }
    }

    const count = new Map();
    const built = [];
    let offscreen = 0;
    for (const it of items) {
      const e = it.e;
      const isDisabled = disabled(e);
      const name = clean(nameOf(e)).slice(0, 160);
      const key = it.role + '\u0000' + name.toLowerCase();
      count.set(key, (count.get(key) || 0) + 1);
      const node = identity(e);
      const r = it.r;

      const offset = it.chain.length ? frameOffset(it.chain) : { x: 0, y: 0 };
      const cx = r.x + r.width / 2 + (offset ? offset.x : 0);
      const cy = r.y + r.height / 2 + (offset ? offset.y : 0);
      const inViewport = !!offset && cx >= 0 && cy >= 0 && cx < innerWidth && cy < innerHeight;
      if (!inViewport) offscreen += 1;

      let occluded = false;
      if (inViewport) {
        try {
          const doc = e.ownerDocument, view = doc.defaultView;
          const lx = r.x + r.width / 2, ly = r.y + r.height / 2;
          if (lx < 0 || ly < 0 || lx >= view.innerWidth || ly >= view.innerHeight) occluded = true;
          else {
            const hit = deepElementFromPoint(doc, lx, ly);
            occluded = !(hit && (hit === e || e.contains(hit) || hit.contains(e)));
          }
        } catch (_) { occluded = false; }
      }

      const options = [];
      if (e.tagName === 'SELECT') {
        for (const o of e.options) {
          if (o.disabled || o.closest('optgroup[disabled]')) continue;
          options.push({
            ref: 'e' + node + ':' + (options.length + 1),
            label: clean(o.label).slice(0, 60), value: o.value, selected: !!o.selected,
          });
        }
      }
      // Login forms are a blind spot for observers that drop password fields.
      // Keep the control usable, but never let its value leave the page.
      const secretField = isPassword(e) || (SECRET_HINT.test(name) && isEditable(e));
      const editable = isEditable(e);
      // A menu that only opens on hover is reachable through its trigger and
      // nothing else, and the trigger announces itself: `aria-haspopup` names
      // the popup, `aria-expanded` tracks it. Those two attributes are the
      // entire signal on purpose -- any looser guess would spend a candidate
      // slot on every page to catch a case it cannot verify.
      const expanded = e.getAttribute('aria-expanded');
      const popup = e.getAttribute('aria-haspopup');
      const hoverable = (popup !== null && popup !== 'false')
        || (expanded !== null && !editable
            && !['checkbox', 'radio', 'switch'].includes(it.role));
      built.push({
        node, ref: 'e' + node, role: it.role, name, label: name || it.role,
        value: secretField ? '' : valueOf(e).slice(0, 300),
        editable, occluded, inViewport, hoverable, disabled: isDisabled,
        multiline: e.tagName === 'TEXTAREA' || !!e.isContentEditable,
        // Role outranks position. The reverse order -- viewport 100 against a
        // primary control's 40 -- let a submit button below the fold lose its
        // slot to a hundred in-viewport navigation links, and made the kept set
        // a function of how far the page happened to be scrolled, so the same
        // page produced a different table on the next read. Position still
        // separates candidates inside a tier, which is why it stays.
        //
        // Disabled controls sit in a tier of their own, below every actionable
        // one. They are worth showing -- see the collection loop above -- but
        // never at the cost of an element the model could actually use, so on a
        // page that fills the cap they are the first to go, exactly as before.
        rank: (isDisabled ? 0 : 10000)
          + (editable || PRIMARY.has(it.role) ? 1000 : 0)
          + (SECONDARY.has(it.role) ? 400 : 0)
          + (inViewport ? 100 : 0),
        order: built.length,
        checked: ['checkbox', 'radio'].includes(typeOf(e)) ? !!e.checked : null,
        expanded,
        current: e.tagName === 'SELECT' ? clean([...e.selectedOptions].map(o => o.label).join(', ')).slice(0, 120) : null,
        multiple: e.tagName === 'SELECT' ? !!e.multiple : false,
        accept: isFile(e) ? (e.getAttribute('accept') || '') : null,
        options: options.slice(0, 40),
        opts_total: options.length,
        secret: secretField,
        scope: clean(scopeOf(e) ? scopeOf(e).innerText : '').slice(0, 120),
      });
    }

    // Context only where a label repeats — shipping it unconditionally is waste.
    for (const b of built) {
      const key = b.role + '\u0000' + b.name.toLowerCase();
      if ((count.get(key) || 0) > 1) b.context = b.scope;
      delete b.scope;
    }

    // Truncate by usefulness, then restore document order for readability, so
    // hitting the cap never drops the form in favour of forty footer links.
    let kept = built;
    let omitted = 0;
    if (built.length > maxActions) {
      kept = [...built].sort((a, b) => (b.rank - a.rank) || (a.order - b.order)).slice(0, maxActions);
      kept.sort((a, b) => a.order - b.order);
      omitted = built.length - kept.length;
    }
    for (const b of kept) delete b.rank;

    const identities = {};
    for (const b of built) identities[b.node] = [b.role, b.name];
    S.snap = { key: keyOf(), guards: {}, identities };

    const actions = kept.map((b, i) => { b.index = i + 1; return b; });
    for (const b of actions) if (!(b.node in S.snap.guards)) S.snap.guards[b.node] = guardOf(S.nodes.get(b.node));

    const digest = built.map(b => [b.role, b.name, b.value, b.checked, b.current,
      b.expanded, b.occluded, b.editable].join('|')).join('\u0001');
    const text = opts.includeText === false ? '' : textOf(maxText);
    return JSON.stringify({
      url: location.href, title: document.title, w: innerWidth, h: innerHeight, text,
      scroll: { y: Math.round(scrollY), height },
      // `reachable` is the number an agent actually cares about: how many of
      // these refs can be acted on without first dismissing something. Disabled
      // controls are in `actions` but not in this count -- they are shown so the
      // model can see what the page is waiting for, and "shown" is not
      // "actionable".
      reachable: actions.filter(b => b.inViewport && !b.occluded && !b.disabled).length,
      actions, omitted, offscreen,
      overlays: overlays(),
      cross_frames: cross.length,
      cross_frame_srcs: cross.slice(0, 3).map(c => c.src).filter(Boolean),
      digest, page_key: S.snap.key,
    });
  };

  /* ----------------------------------------------------- guard + geometry */

  const nodeFor = ref => S.nodes.get(
    typeof ref === 'number' ? ref : parseInt(String(ref).replace(/^e/, ''), 10));

  const refId = ref => String(String(ref).replace(/^e/, '').split(':')[0]);

  const verify = (ref, pageKey) => {
    const e = nodeFor(ref);
    if (!e || !e.isConnected) return { ok: false, reason: 'detached' };
    if (pageKey && keyOf() !== pageKey) return { ok: false, reason: 'page_changed' };
    const before = S.snap && S.snap.guards[refId(ref)];
    const now = guardOf(e);
    if (before == null || now !== before) return { ok: false, reason: 'target_changed' };
    return { ok: true };
  };

  // Used for the 2nd..nth op of a batch. Earlier ops in the same batch are
  // allowed to have changed values and checked state; what must still hold is
  // that this ref is the same control the agent chose.
  const reinspect = ref => {
    const e = nodeFor(ref);
    if (!e || !e.isConnected) return { ok: false, reason: 'detached' };
    if (disabled(e)) return { ok: false, reason: 'disabled' };
    if (!deepVisible(e)) return { ok: false, reason: 'hidden' };
    const known = S.snap && S.snap.identities[refId(ref)];
    if (!known) return { ok: false, reason: 'unknown_ref' };
    if (known[0] !== roleOf(e) || known[1] !== clean(nameOf(e)).slice(0, 160)) {
      return { ok: false, reason: 'target_changed' };
    }
    return { ok: true };
  };

  const resolve = ref => {
    const e = nodeFor(ref);
    if (!e || !e.isConnected) return { ok: false, reason: 'detached' };
    if (disabled(e)) return { ok: false, reason: 'disabled' };
    if (!deepVisible(e)) return { ok: false, reason: 'hidden' };
    const doc = e.ownerDocument, view = doc.defaultView;
    const r = e.getBoundingClientRect();
    if (!r.width || !r.height) return { ok: false, reason: 'no_geometry' };
    const lx = r.x + r.width / 2, ly = r.y + r.height / 2;
    if (lx < 0 || ly < 0 || lx >= view.innerWidth || ly >= view.innerHeight) {
      return { ok: false, reason: 'out_of_viewport' };
    }
    const hit = deepElementFromPoint(doc, lx, ly);
    if (!hit || !(hit === e || e.contains(hit) || hit.contains(e))) {
      return { ok: false, reason: 'occluded' };
    }
    const off = offsetFor(frameChainOf(e));
    if (!off.ok) return { ok: false, reason: off.reason };
    return { ok: true, x: Math.round(lx + off.x), y: Math.round(ly + off.y) };
  };

  const scrollTo = ref => {
    const e = nodeFor(ref);
    if (!e || !e.isConnected) return { ok: false, reason: 'detached' };
    try {
      e.scrollIntoView({ block: 'center', inline: 'center' });
      // scrollIntoView does not reliably cross frame boundaries, so bring every
      // containing frame into view too.
      for (const f of frameChainOf(e)) {
        try { f.scrollIntoView({ block: 'center', inline: 'center' }); } catch (_) { break; }
      }
    } catch (_) {
      return { ok: false, reason: 'scroll_failed' };
    }
    return { ok: true };
  };

  const selectOption = (ref, value) => {
    const e = nodeFor(ref);
    if (!e || e.tagName !== 'SELECT') return { ok: false, reason: 'not_a_select' };
    const options = [...e.options];
    const match = options.find(o => o.value === String(value) && !o.disabled && !o.closest('optgroup[disabled]'))
      || options.find(o => clean(o.label) === clean(String(value)) && !o.disabled && !o.closest('optgroup[disabled]'))
      || options.find(o => clean(o.label).toLowerCase() === clean(String(value)).toLowerCase());
    if (!match) return { ok: false, reason: 'no_such_option' };
    if (e.multiple) {
      match.selected = true;
    } else {
      e.value = match.value;
    }
    e.dispatchEvent(new Event('input', { bubbles: true }));
    e.dispatchEvent(new Event('change', { bubbles: true }));
    return { ok: true, value: match.value, label: clean(match.label) };
  };

  const settle = kind => new Promise(resolveDone => {
    let frames = 0, stopped = false;
    const finish = () => { if (!stopped) { stopped = true; resolveDone(); } };
    setTimeout(finish, kind === 'options' ? 200 : 50);
    const step = () => {
      if (stopped) return;
      if (++frames >= 2) return finish();
      requestAnimationFrame(step);
    };
    requestAnimationFrame(step);
  });

  const label = ref => {
    const e = nodeFor(ref);
    return e && e.isConnected ? clean(nameOf(e)).slice(0, 120) : '';
  };

  // What has focus, in the shape the server's secret check reads.
  //
  // `keys` puts text on the page: a bare single character with no modifier goes
  // out as `Input.insertText`, not as a key press. That makes it a second way to
  // type, and it has no ref -- the field it writes into is whatever happens to
  // be focused. The rail that guards `type` therefore has to be able to ask this
  // question, and it could not: a password could be filled a character at a time
  // with no confirmation, and the characters were written into a recorded macro
  // verbatim. `secret` is the same expression the element table uses, so the
  // field `keys` refuses is the field whose value the table masks.
  //
  // Three answers, because two would collapse cases that need different
  // handling: `{focused: true, ...}` for a field, `{focused: false}` when
  // nothing is focused and the text would go nowhere, and `{unknown: true}` when
  // focus is inside a frame this document cannot read. That last one is not a
  // claim that the field is ordinary. Neither sentinel is `null`, because a
  // `null` from the page and a failed evaluation look the same to the caller.
  const active = () => {
    let e = document.activeElement;
    try {
      for (let hops = 0; e && e.tagName === 'IFRAME' && hops < 10; hops += 1) {
        const inner = e.contentDocument;
        if (!inner) return { unknown: true };
        e = inner.activeElement;
      }
    } catch (_) { return { unknown: true }; }
    if (!e || e === e.ownerDocument.body || e === e.ownerDocument.documentElement) {
      return { focused: false };
    }
    const name = clean(nameOf(e)).slice(0, 120);
    return {
      focused: true,
      name,
      role: roleOf(e) || '',
      secret: isPassword(e) || (SECRET_HINT.test(name) && isEditable(e)),
    };
  };

  // The names of the controls Enter in this field would stand in for.
  //
  // Enter in a text field submits its form as if the form's default button had been clicked
  // (implicit submission), and a page's own Enter handler usually does the same for its dialog. So
  // `type` with `submit` must answer to the rail that guards clicking those buttons, or "Pay now"
  // needs confirming when clicked and not when the Amount field is sent. Reported as names, and the
  // server runs its own confirmation rules over them, so there is one rule list and it lives there.
  // `null` (not `[]`) when the ref is gone: "nothing to confirm" and "could not look" differ.
  const submitters = ref => {
    const e = nodeFor(ref);
    if (!e || !e.isConnected) return null;
    const form = e.form || e.closest('form');
    const scope = form || e.closest('dialog,[role="dialog"],[role="alertdialog"]');
    if (!scope) return [];
    const found = new Set(scope.querySelectorAll(
      'button,input[type="submit"],input[type="image"],[role="button"]'));
    // `form=` attributes put a form's buttons anywhere in the document.
    if (form) for (const x of form.elements) if (x.tagName === 'BUTTON' || x.type === 'submit') found.add(x);
    return [...found].map(x => clean(nameOf(x) || x.value || '').slice(0, 120)).filter(Boolean);
  };

  const stats = () => ({ refs: S.nodes.size, next: S.next, hasSnap: !!S.snap });

  W.__jevMcp = {
    version: VERSION, readState, verify, reinspect, resolve, scrollTo, selectOption,
    settle, label, active, submitters, stats, keyOf, guardOf,
  };
})();
