/* jev-ultrafast-mcp — in-page observer + guarded execution support.
 *
 * Installed on the TOP-LEVEL window only (same-origin frames reach it through
 * window.top). Responsibilities:
 *
 *   1. readState()   — one atomic read of visible text + actionable elements,
 *                      each with a code-owned, observation-stable ref.
 *   2. verify()      — strict freshness: still the page and element observed?
 *   3. reinspect()   — relaxed freshness: still the same control? Used for the
 *                      second and later ops of a batch, where earlier ops have
 *                      legitimately mutated the page.
 *   4. resolve()     — geometry + occlusion, recomputed just before input.
 *
 * Design rules (carried over from browser-use/jev-ultrafast):
 *   - Refs are owned by code, never generated by a model.
 *   - Geometry is always re-resolved immediately before input.
 *   - Page text is untrusted data, never instructions.
 */
(() => {
  const W = window;
  // Which helper this is. One declaration, because two copies of a version
  // number are two versions waiting to disagree: the guard below and the value
  // this file reports have to be the same fact, and `browser.HELPER_VERSION`
  // has to match both. It was three separate literals, and the server's had
  // been bumped while these two had not -- so the check could never be
  // satisfied, the server re-injected this whole file on every observation, and
  // a page holding the older helper was never actually upgraded, because the
  // early return fired on the number it already carried.
  const VERSION = 15;
  try { if (W !== W.top) return; } catch (_) { return; }
  if (W.__jevMcp && W.__jevMcp.version === VERSION) return;

  // Refs survive a helper re-injection, so an agent can keep referring to e37
  // across observes. `next` is monotonic: a pruned ref is never recycled.
  const S = W.__jevRefs || (W.__jevRefs = { ids: new WeakMap(), nodes: new Map(), next: 1, snap: null });

  const ROLES = ['button', 'link', 'checkbox', 'radio', 'switch', 'tab', 'menuitem',
    'menuitemcheckbox', 'menuitemradio', 'option', 'treeitem', 'gridcell', 'combobox',
    'textbox', 'searchbox', 'spinbutton', 'listbox'];
  const SELECTOR = 'a[href],button,input,textarea,select,summary,[contenteditable=""],' +
    '[contenteditable="true"],' + ROLES.map(r => '[role="' + r + '"]').join(',');
  const UNSAFE_TYPES = ['hidden'];

  // Word-bounded on purpose: /pass/ alone flags "Passengers", /code/ alone
  // flags every "Promo code" field -- and `safety.is_secret` on the server side
  // matches the same names, because the observation masks on the union of this flag
  // and that list. A name only this side matches is a field whose value the agent
  // cannot read.
  const SECRET_HINT = new RegExp([
    '\\bpassword\\b', '\\bpasswd\\b', '\\bpasscode\\b', '\\bpassphrase\\b',
    '\\botp\\b', '\\bone[- ]?time\\b', '\\bverification code\\b', '\\bsecurity code\\b',
    '\\bcvv\\b', '\\bcvc\\b', '\\bcard\\s*number\\b', '\\bsecret\\b',
    '\\bapi\\s*key\\b', '\\baccess\\s*token\\b', '\\bssn\\b', '\\bsocial security\\b',
    '\\biban\\b', '\\brouting\\s*number\\b', '\\bsecurity\\s*answer\\b', '\\bpin\\b',
  ].join('|'), 'i');

  const PRIMARY = new Set(['button', 'combobox', 'listbox', 'textbox', 'searchbox',
    'checkbox', 'radio', 'switch', 'spinbutton', 'file', 'listbox']);
  const SECONDARY = new Set(['option', 'tab', 'menuitem', 'menuitemcheckbox',
    'menuitemradio', 'treeitem', 'gridcell', 'radio', 'checkbox', 'switch']);

  /* ---------------------------------------------------------------- helpers */

  const clean = s => (s || '').replace(/\s+/g, ' ').trim();

  const identity = e => {
    if (!S.ids.has(e)) { S.ids.set(e, S.next++); S.nodes.set(S.ids.get(e), e); }
    return S.ids.get(e);
  };

  const prune = () => { for (const [id, e] of S.nodes) if (!e.isConnected) S.nodes.delete(id); };

  // The input's *effective* type, which is what the browser renders and edits. The raw attribute
  // is not: HTML's default is `text`, so `<input name="q">`, `type=""` and an unrecognised type
  // are all text boxes, and reading the attribute left them with no role -- never editable, never
  // offered to TYPE_TEXT. `.type` is already lower-cased and resolved by the browser. Non-inputs
  // (a `<button type=submit>`, a `<ul>` with a stray attribute) keep reading the attribute.
  // Captured once, when the helper loads: a page can override `getAttribute` or `type` on an
  // element (or its prototype chain below these) to disguise a password field.
  const GET_ATTRIBUTE = Element.prototype.getAttribute;
  const INPUT_TYPE = Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'type').get;
  const rawAttr = (e, name) => { try { return GET_ATTRIBUTE.call(e, name); } catch (_) { return null; } };
  const typeOf = e => {
    if (e && e.tagName === 'INPUT') {
      try { const t = INPUT_TYPE.call(e); if (typeof t === 'string') return t.toLowerCase(); } catch (_) { /* not a real input */ }
    }
    return (rawAttr(e, 'type') || '').toLowerCase();
  };
  const isFile = e => e.tagName === 'INPUT' && typeOf(e) === 'file';
  // Secret if *either* reading says password. `.type` is what the browser edits, but it is a
  // getter a page can override; the attribute is what the markup declared. Masking on the union
  // means neither one alone can un-mask a password field.
  const isPassword = e => typeOf(e) === 'password'
    || (rawAttr(e, 'type') || '').toLowerCase() === 'password'
    || (e && typeof e.type === 'string' && e.type.toLowerCase() === 'password');

  // Per-read memo. One readState asks about thousands of elements that share ancestors, and the
  // walk below re-checked every ancestor for each of them: measured on a long Wikipedia article
  // (3,800 candidates, 13,000 text nodes), this function and the `closest`/`checkVisibility`
  // calls it makes were over half of an 850 ms read. The DOM cannot change while one synchronous
  // read runs, so each node's answer is computed once and reused. `null` outside a read, where
  // callers (verify, reinspect, the click rail) keep the uncached walk.
  let VIS = null;
  const visibleMemo = n => {
    if (!n || n.nodeType !== 1) return true;
    const known = VIS.get(n);
    if (known !== undefined) return known;
    let ok = !(GET_ATTRIBUTE.call(n, 'aria-hidden') === 'true' || GET_ATTRIBUTE.call(n, 'inert') !== null);
    if (ok) { try { ok = n.checkVisibility({ checkOpacity: true, checkVisibilityCSS: true }); } catch (_) { ok = false; } }
    if (ok) {
      let up = n.parentElement;
      if (!up) { const root = n.getRootNode && n.getRootNode(); up = root && root instanceof ShadowRoot ? root.host : null; }
      ok = visibleMemo(up);
    }
    VIS.set(n, ok);
    return ok;
  };

  const deepVisible = e => {
    if (VIS) return visibleMemo(e);
    let n = e;
    while (n && n.nodeType === 1) {
      if (n.closest && n.closest('[aria-hidden="true"],[inert]')) return false;
      try { if (!n.checkVisibility({ checkOpacity: true, checkVisibilityCSS: true })) return false; } catch (_) { return false; }
      if (n.parentElement) { n = n.parentElement; continue; }
      const root = n.getRootNode && n.getRootNode();
      n = root && root instanceof ShadowRoot ? root.host : null;
    }
    return true;
  };

  // `document.elementFromPoint` stops at a shadow host, so a control inside a
  // web component looks permanently "covered". Descend the shadow tree.
  const deepElementFromPoint = (doc, x, y) => {
    let element = doc.elementFromPoint(x, y);
    let guard = 0;
    while (element && element.shadowRoot && guard++ < 12) {
      const inner = element.shadowRoot.elementFromPoint(x, y);
      if (!inner || inner === element) break;
      element = inner;
    }
    return element;
  };

  // Whether an element the page draws with `pointer-events: none` passes its clicks through to its
  // own row. Such an element can never be the hit: a link laid over a result row as a transparent
  // overlay carrying the accessible name (Google Flights draws every result this way), with the
  // real handler on its sibling. The row is its parent and nothing wider -- a hit anywhere else
  // (a modal, a cookie banner, any other overlay) is a cover, as it is for every other element.
  // Not when the parent is the page itself: then "inside the parent" is "anywhere", modals included.
  const passThrough = e => {
    let none = false;
    try { none = e.ownerDocument.defaultView.getComputedStyle(e).pointerEvents === 'none'; } catch (_) { none = false; }
    if (!none) return null;
    const p = e.parentElement, doc = e.ownerDocument;
    return p && p !== doc.body && p !== doc.documentElement ? p : null;
  };
  // Whether a click at the centre of `e`, which hit `hit`, lands on `e` (or on its own row, above).
  const reaches = (e, hit) => {
    if (!hit) return false;
    if (hit === e || e.contains(hit) || hit.contains(e)) return true;
    const row = passThrough(e);
    return !!(row && row.contains(hit));
  };

  const roleOf = e => {
    const explicit = e.getAttribute('role');
    if (explicit && ROLES.includes(explicit)) return explicit;
    const tag = e.tagName;
    if (tag === 'BUTTON' || tag === 'SUMMARY') return 'button';
    if (tag === 'A') return 'link';
    if (tag === 'SELECT') return e.multiple ? 'listbox' : 'combobox';
    if (tag === 'TEXTAREA' || e.isContentEditable) return 'textbox';
    if (tag === 'INPUT') {
      const t = typeOf(e);
      if (t === 'checkbox') return 'checkbox';
      if (t === 'radio') return 'radio';
      if (['button', 'submit', 'reset', 'image'].includes(t)) return 'button';
      if (t === 'search') return 'searchbox';
      if (t === 'number') return 'spinbutton';
      if (t === 'file') return 'file';
      if (['text', 'email', 'url', 'tel', 'date', 'datetime-local', 'month',
        'week', 'time', 'password'].includes(t)) return 'textbox';
    }
    return null;
  };

  const FLAT = ['button', 'submit', 'reset', 'image'];

  const nameOf = (e, seen) => {
    seen = seen || new Set();
    if (!e || seen.has(e)) return '';
    seen.add(e);
    const byId = (e.getAttribute('aria-labelledby') || '').split(/\s+/)
      .map(id => nameOf(document.getElementById(id), seen)).filter(Boolean).join(' ');
    if (byId) return byId;
    const label = e.getAttribute('aria-label');
    if (label) return label;
    if (e.labels && e.labels.length) {
      const fromLabel = [...e.labels].map(l => nameOf(l, seen)).filter(Boolean).join(' ');
      if (fromLabel) return fromLabel;
    }
    if (FLAT.includes(typeOf(e)) && e.value) return e.value;
    if (e.getAttribute('alt')) return e.getAttribute('alt');
    if (e.tagName !== 'INPUT' && e.tagName !== 'TEXTAREA') {
      const fromText = [...e.childNodes].map(n => n.nodeType === 3 ? n.textContent
        : n.nodeType === 1 && n.getAttribute('aria-hidden') !== 'true' ? nameOf(n, seen) : '').join(' ').trim();
      if (fromText) return fromText;
    }
    return e.getAttribute('title') || e.getAttribute('placeholder') || '';
  };

  const valueOf = e => {
    if (isFile(e)) return e.files && e.files.length ? [...e.files].map(f => f.name).join(', ') : '';
    if ('value' in e && !['checkbox', 'radio'].includes(typeOf(e))) return String(e.value == null ? '' : e.value);
    if (e.isContentEditable) return clean(e.innerText);
    if (roleOf(e) === 'combobox' && e.tagName !== 'SELECT') return clean(e.innerText);
    return '';
  };

  const disabled = e => e.matches(':disabled') || !!e.closest('[aria-disabled="true"],[inert]');

  const isEditable = e => {
    if (isFile(e) || e.tagName === 'SELECT') return false;
    const role = roleOf(e);
    if (!['textbox', 'searchbox', 'spinbutton', 'combobox'].includes(role)) return false;
    if (role === 'combobox' && !['INPUT', 'TEXTAREA'].includes(e.tagName)) return false;
    if (e.readOnly || e.getAttribute('aria-readonly') === 'true') return false;
    if (disabled(e)) return false;
    return true;
  };

  /* ------------------------------------------------------- frame traversal */

  const frameChainOf = e => {
    const chain = [];
    let view = e.ownerDocument && e.ownerDocument.defaultView;
    let guard = 0;
    while (view && view !== W && guard++ < 12) {
      let fe = null;
      try { fe = view.frameElement; } catch (_) { fe = null; }
      if (!fe) break;
      chain.unshift(fe);
      try { view = fe.ownerDocument.defaultView; } catch (_) { break; }
    }
    return chain;
  };

  // Cheap offset: geometry only, no hit test. Used for ranking.
  const frameOffset = chain => {
    let x = 0, y = 0;
    for (const f of chain) {
      if (!f.isConnected || !deepVisible(f)) return null;
      const r = f.getBoundingClientRect();
      x += r.x; y += r.y;
    }
    return { x, y };
  };

  // Strict offset: also proves every frame in the chain is actually hit-testable.
  const offsetFor = chain => {
    let x = 0, y = 0;
    for (const f of chain) {
      if (!f.isConnected || !deepVisible(f)) return { ok: false, reason: 'frame_hidden' };
      const r = f.getBoundingClientRect();
      const doc = f.ownerDocument, view = doc.defaultView;
      const hx = r.x + r.width / 2, hy = r.y + r.height / 2;
      if (hx < 0 || hy < 0 || hx >= view.innerWidth || hy >= view.innerHeight) {
        return { ok: false, reason: 'frame_out_of_viewport' };
      }
      const hit = deepElementFromPoint(doc, hx, hy);
      if (!hit || !(hit === f || f.contains(hit))) return { ok: false, reason: 'frame_occluded' };
      x += r.x; y += r.y;
    }
    return { ok: true, x, y };
  };

  const rootList = () => {
    const out = [];
    const cross = [];
    const visit = (doc, chain, depth) => {
      if (depth > 6) return;
      out.push({ doc, chain });
      let frames = [];
      try { frames = doc.querySelectorAll('iframe,frame'); } catch (_) { return; }
      for (const f of frames) {
        let cd = null;
        try { cd = f.contentDocument; } catch (_) { cd = null; }
        if (cd && cd.body) visit(cd, chain.concat([f]), depth + 1);
        else cross.push({ chain: chain.concat([f]), src: f.getAttribute('src') || '' });
      }
    };
    visit(document, [], 0);
    return { roots: out, cross };
  };

  const rootsOf = root => {
    const out = [root];
    let all = [];
    try { all = root.querySelectorAll('*'); } catch (_) { return out; }
    if (all.length > 20000) return out;
    for (const e of all) if (e.shadowRoot) out.push(...rootsOf(e.shadowRoot));
    return out;
  };

  /* ------------------------------------------------------------ page state */

  const pageFields = () => [...document.querySelectorAll('input,textarea,select')]
    .filter(e => !UNSAFE_TYPES.includes(typeOf(e)))
    .map(e => [identity(e), valueOf(e), !!e.checked, e.selectedIndex, e.disabled, e.readOnly]);

  // Scroll is deliberately excluded: geometry is re-resolved before every
  // input anyway, so a scroll (ours or the page's) is not a semantic change
  // and must not invalidate a decision. Form values are included, because
  // those genuinely change what a ref means.
  const keyOf = () => JSON.stringify([performance.timeOrigin, location.href,
    innerWidth, innerHeight, pageFields()]);

  // What tells two identically named controls apart: the row or card they sit in, before any form.
  // A mail list puts each row's Star/Archive buttons in their own tiny form whose text is just
  // "Star Archive", which made every row's context the same.
  const scopeOf = e => e.closest('tr,[role="row"],li,[role="listitem"],article')
    || e.closest('form,dialog,[role="dialog"]') || e.parentElement;

  const guardOf = e => {
    if (!e || !e.isConnected || !deepVisible(e)) return null;
    const scope = scopeOf(e);
    return JSON.stringify([identity(e), roleOf(e), nameOf(e), valueOf(e),
      typeOf(e) && ['checkbox', 'radio'].includes(typeOf(e)) ? !!e.checked : null,
      e.selectedIndex == null ? null : e.selectedIndex, !!e.readOnly, disabled(e),
      e.getAttribute('aria-disabled'), e.getAttribute('aria-expanded'),
      e.getAttribute('aria-checked'), e.getAttribute('aria-selected'), e.getAttribute('href'),
      scope ? clean(scope.innerText).slice(0, 400) : '']);
  };

  const secretEditable = n => {
    let host = n;
    while (host.parentElement && host.parentElement.isContentEditable) host = host.parentElement;
    return SECRET_HINT.test(clean(nameOf(host)));
  };

  const textOf = max => {
    const words = [];
    const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
    const range = document.createRange();
    let node, length = 0;
    while ((node = walker.nextNode()) && length < max) {
      const value = clean(node.textContent), parent = node.parentElement;
      if (!value || !parent || parent.closest('script,style,noscript,template')) continue;
      if (!deepVisible(parent)) continue;
      // A contenteditable "Card number" is masked in the element table; its text must not come
      // back through the page text instead (the third review read the card number here).
      if (parent.isContentEditable && secretEditable(parent)) continue;
      range.selectNodeContents(node);
      const r = range.getBoundingClientRect();
      if (r.width > 0 && r.height > 0 && r.bottom > 0 && r.top < innerHeight && r.right > 0 && r.left < innerWidth) {
        words.push(value); length += value.length;
      }
    }
    return words.join('\n').slice(0, max);
  };

  const overlays = () => [...document.querySelectorAll('dialog[open],[role="dialog"],[role="alertdialog"],[aria-modal="true"]')]
    .filter(e => deepVisible(e))
    .slice(0, 3)
    .map(e => ({
      role: e.getAttribute('role') || 'dialog',
      name: clean(nameOf(e)).slice(0, 80),
      modal: e.getAttribute('aria-modal') === 'true' || e.tagName === 'DIALOG',
    }));

  /* ------------------------------------------------------------ readState */

  const readState = opts => {
    VIS = new Map();
    try { return readStateOnce(opts); } finally { VIS = null; }
  };

  const readStateOnce = opts => {
    opts = opts || {};
    const maxActions = opts.maxActions || 250;
    const maxText = opts.maxText || 6000;
    // Words from the goal being run. On a page with more controls than the cap (Mount Everest's
    // article: 2,683), the link a goal names -- "Tenzing Norgay" -- ranked with every other
    // off-screen link and was cut, so the model never saw it and answered BLOCKED. A name that
    // carries goal words is kept ahead of ones that do not; nothing else about ranking changes.
    const prefer = (Array.isArray(opts.prefer) ? opts.prefer : [])
      .map(w => String(w).toLowerCase()).filter(w => w.length >= 3).slice(0, 24);
    prune();
    const { roots, cross } = rootList();
    const height = document.documentElement.scrollHeight;

    const items = [];
    const seen = new Set();
    for (const { doc, chain } of roots) {
      for (const root of rootsOf(doc)) {
        let found = [];
        try { found = root.querySelectorAll(SELECTOR); } catch (_) { continue; }
        for (const e of found) {
          if (seen.has(e)) continue;
          if (UNSAFE_TYPES.includes(typeOf(e))) continue;
          // Disabled controls are kept rather than dropped. A control that
          // exists and cannot be used is information the model needs: a submit
          // button that only enables once an option is chosen is the ordinary
          // shape of a form, and dropping it silently is how the model ends up
          // able to select an option and with nothing to submit. `resolve`
          // already refuses one with reason 'disabled', so keeping it costs a
          // clear refusal rather than a wrong click.
          if (!e.isConnected || !deepVisible(e)) continue;
          const role = roleOf(e);
          if (!role) continue;
          if (role === 'gridcell' && e.querySelector('button,[role="button"]')) continue;
          const r = e.getBoundingClientRect();
          if (!r.width || !r.height) continue;
          seen.add(e);
          items.push({ e, role, chain, r });
        }
        if (items.length > maxActions * 6) break;
      }
    }

    const count = new Map();
    const built = [];
    let offscreen = 0;
    for (const it of items) {
      const e = it.e;
      const isDisabled = disabled(e);
      const name = clean(nameOf(e)).slice(0, 160);
      const key = it.role + '\u0000' + name.toLowerCase();
      count.set(key, (count.get(key) || 0) + 1);
      const node = identity(e);
      const r = it.r;

      const offset = it.chain.length ? frameOffset(it.chain) : { x: 0, y: 0 };
      const cx = r.x + r.width / 2 + (offset ? offset.x : 0);
      const cy = r.y + r.height / 2 + (offset ? offset.y : 0);
      const inViewport = !!offset && cx >= 0 && cy >= 0 && cx < innerWidth && cy < innerHeight;
      if (!inViewport) offscreen += 1;

      let occluded = false;
      if (inViewport) {
        try {
          const doc = e.ownerDocument, view = doc.defaultView;
          const lx = r.x + r.width / 2, ly = r.y + r.height / 2;
          if (lx < 0 || ly < 0 || lx >= view.innerWidth || ly >= view.innerHeight) occluded = true;
          else {
            const hit = deepElementFromPoint(doc, lx, ly);
            occluded = !reaches(e, hit);
          }
        } catch (_) { occluded = false; }
      }

      const options = [];
      if (e.tagName === 'SELECT') {
        for (const o of e.options) {
          if (o.disabled || o.closest('optgroup[disabled]')) continue;
          options.push({
            ref: 'e' + node + ':' + (options.length + 1),
            label: clean(o.label).slice(0, 60), value: o.value, selected: !!o.selected,
          });
        }
      }
      // Login forms are a blind spot for observers that drop password fields.
      // Keep the control usable, but never let its value leave the page.
      const secretField = isPassword(e) || (SECRET_HINT.test(name) && isEditable(e));
      const editable = isEditable(e);
      // A menu that only opens on hover is reachable through its trigger and
      // nothing else, and the trigger announces itself: `aria-haspopup` names
      // the popup, `aria-expanded` tracks it. Those two attributes are the
      // entire signal on purpose -- any looser guess would spend a candidate
      // slot on every page to catch a case it cannot verify.
      const expanded = e.getAttribute('aria-expanded');
      const popup = e.getAttribute('aria-haspopup');
      const hoverable = (popup !== null && popup !== 'false')
        || (expanded !== null && !editable
            && !['checkbox', 'radio', 'switch'].includes(it.role));
      built.push({
        node, ref: 'e' + node, role: it.role, name, label: name || it.role,
        value: secretField ? '' : valueOf(e).slice(0, 300),
        editable, occluded, inViewport, hoverable, disabled: isDisabled,
        multiline: e.tagName === 'TEXTAREA' || !!e.isContentEditable,
        // Role outranks position. The reverse order -- viewport 100 against a
        // primary control's 40 -- let a submit button below the fold lose its
        // slot to a hundred in-viewport navigation links, and made the kept set
        // a function of how far the page happened to be scrolled, so the same
        // page produced a different table on the next read. Position still
        // separates candidates inside a tier, which is why it stays.
        //
        // Disabled controls sit in a tier of their own, below every actionable
        // one. They are worth showing -- see the collection loop above -- but
        // never at the cost of an element the model could actually use, so on a
        // page that fills the cap they are the first to go, exactly as before.
        rank: (isDisabled ? 0 : 10000)
          + (editable || PRIMARY.has(it.role) ? 1000 : 0)
          + (SECONDARY.has(it.role) ? 400 : 0)
          + (inViewport ? 100 : 0)
          + (prefer.length ? 1500 * Math.min(3, prefer.filter(w => name.toLowerCase().includes(w)).length) : 0),
        order: built.length,
        checked: ['checkbox', 'radio'].includes(typeOf(e)) ? !!e.checked : null,
        expanded,
        current: e.tagName === 'SELECT' ? clean([...e.selectedOptions].map(o => o.label).join(', ')).slice(0, 120) : null,
        multiple: e.tagName === 'SELECT' ? !!e.multiple : false,
        accept: isFile(e) ? (e.getAttribute('accept') || '') : null,
        options: options.slice(0, 40),
        opts_total: options.length,
        secret: secretField,
      });
    }

    // Context only where a label repeats — shipping it unconditionally is waste.
    for (const b of built) {
      const key = b.role + '\u0000' + b.name.toLowerCase();
      // Read only here: `innerText` forces layout, and reading it for every candidate was a
      // tenth of a read on a large page to fill a field that most elements then discarded.
      if ((count.get(key) || 0) > 1) {
        const scope = scopeOf(S.nodes.get(b.node));
        b.context = clean(scope ? scope.innerText : '').slice(0, 120);
      }
    }

    // Truncate by usefulness, then restore document order for readability, so
    // hitting the cap never drops the form in favour of forty footer links.
    let kept = built;
    let omitted = 0;
    if (built.length > maxActions) {
      kept = [...built].sort((a, b) => (b.rank - a.rank) || (a.order - b.order)).slice(0, maxActions);
      kept.sort((a, b) => a.order - b.order);
      omitted = built.length - kept.length;
    }
    for (const b of kept) delete b.rank;

    const identities = {};
    for (const b of built) identities[b.node] = [b.role, b.name];
    S.snap = { key: keyOf(), guards: {}, identities };

    const actions = kept.map((b, i) => { b.index = i + 1; return b; });
    for (const b of actions) if (!(b.node in S.snap.guards)) S.snap.guards[b.node] = guardOf(S.nodes.get(b.node));

    const digest = built.map(b => [b.role, b.name, b.value, b.checked, b.current,
      b.expanded, b.occluded, b.editable].join('|')).join('\u0001');
    const text = opts.includeText === false ? '' : textOf(maxText);
    return JSON.stringify({
      url: location.href, title: document.title, w: innerWidth, h: innerHeight, text,
      scroll: { y: Math.round(scrollY), height },
      // `reachable` is the number an agent actually cares about: how many of
      // these refs can be acted on without first dismissing something. Disabled
      // controls are in `actions` but not in this count -- they are shown so the
      // model can see what the page is waiting for, and "shown" is not
      // "actionable".
      reachable: actions.filter(b => b.inViewport && !b.occluded && !b.disabled).length,
      actions, omitted, offscreen,
      overlays: overlays(),
      cross_frames: cross.length,
      cross_frame_srcs: cross.slice(0, 3).map(c => c.src).filter(Boolean),
      digest, page_key: S.snap.key,
    });
  };

  /* ----------------------------------------------------- guard + geometry */

  const nodeFor = ref => S.nodes.get(
    typeof ref === 'number' ? ref : parseInt(String(ref).replace(/^e/, ''), 10));

  const refId = ref => String(String(ref).replace(/^e/, '').split(':')[0]);

  const verify = (ref, pageKey) => {
    const e = nodeFor(ref);
    if (!e || !e.isConnected) return { ok: false, reason: 'detached' };
    if (pageKey && keyOf() !== pageKey) return { ok: false, reason: 'page_changed' };
    const before = S.snap && S.snap.guards[refId(ref)];
    const now = guardOf(e);
    if (before == null || now !== before) return { ok: false, reason: 'target_changed' };
    return { ok: true };
  };

  // Used for the 2nd..nth op of a batch. Earlier ops in the same batch are
  // allowed to have changed values and checked state; what must still hold is
  // that this ref is the same control the agent chose.
  const reinspect = ref => {
    const e = nodeFor(ref);
    if (!e || !e.isConnected) return { ok: false, reason: 'detached' };
    if (disabled(e)) return { ok: false, reason: 'disabled' };
    if (!deepVisible(e)) return { ok: false, reason: 'hidden' };
    const known = S.snap && S.snap.identities[refId(ref)];
    if (!known) return { ok: false, reason: 'unknown_ref' };
    if (known[0] !== roleOf(e) || known[1] !== clean(nameOf(e)).slice(0, 160)) {
      return { ok: false, reason: 'target_changed' };
    }
    return { ok: true };
  };

  const resolve = ref => {
    const e = nodeFor(ref);
    if (!e || !e.isConnected) return { ok: false, reason: 'detached' };
    if (disabled(e)) return { ok: false, reason: 'disabled' };
    if (!deepVisible(e)) return { ok: false, reason: 'hidden' };
    const doc = e.ownerDocument, view = doc.defaultView;
    const r = e.getBoundingClientRect();
    if (!r.width || !r.height) return { ok: false, reason: 'no_geometry' };
    const lx = r.x + r.width / 2, ly = r.y + r.height / 2;
    if (lx < 0 || ly < 0 || lx >= view.innerWidth || ly >= view.innerHeight) {
      return { ok: false, reason: 'out_of_viewport' };
    }
    const hit = deepElementFromPoint(doc, lx, ly);
    if (!reaches(e, hit)) {
      return { ok: false, reason: 'occluded' };
    }
    const off = offsetFor(frameChainOf(e));
    if (!off.ok) return { ok: false, reason: off.reason };
    return { ok: true, x: Math.round(lx + off.x), y: Math.round(ly + off.y) };
  };

  const scrollTo = ref => {
    const e = nodeFor(ref);
    if (!e || !e.isConnected) return { ok: false, reason: 'detached' };
    try {
      e.scrollIntoView({ block: 'center', inline: 'center' });
      // scrollIntoView does not reliably cross frame boundaries, so bring every
      // containing frame into view too.
      for (const f of frameChainOf(e)) {
        try { f.scrollIntoView({ block: 'center', inline: 'center' }); } catch (_) { break; }
      }
    } catch (_) {
      return { ok: false, reason: 'scroll_failed' };
    }
    return { ok: true };
  };

  const selectOption = (ref, value) => {
    const e = nodeFor(ref);
    if (!e || e.tagName !== 'SELECT') return { ok: false, reason: 'not_a_select' };
    const options = [...e.options];
    const match = options.find(o => o.value === String(value) && !o.disabled && !o.closest('optgroup[disabled]'))
      || options.find(o => clean(o.label) === clean(String(value)) && !o.disabled && !o.closest('optgroup[disabled]'))
      || options.find(o => clean(o.label).toLowerCase() === clean(String(value)).toLowerCase());
    if (!match) return { ok: false, reason: 'no_such_option' };
    if (e.multiple) {
      match.selected = true;
    } else {
      e.value = match.value;
    }
    e.dispatchEvent(new Event('input', { bubbles: true }));
    e.dispatchEvent(new Event('change', { bubbles: true }));
    return { ok: true, value: match.value, label: clean(match.label) };
  };

  const settle = kind => new Promise(resolveDone => {
    let frames = 0, stopped = false;
    const finish = () => { if (!stopped) { stopped = true; resolveDone(); } };
    setTimeout(finish, kind === 'options' ? 200 : 50);
    const step = () => {
      if (stopped) return;
      if (++frames >= 2) return finish();
      requestAnimationFrame(step);
    };
    requestAnimationFrame(step);
  });

  const label = ref => {
    const e = nodeFor(ref);
    return e && e.isConnected ? clean(nameOf(e)).slice(0, 120) : '';
  };

  // What has focus, in the shape the server's secret check reads.
  //
  // `keys` puts text on the page: a bare single character with no modifier goes
  // out as `Input.insertText`, not as a key press. That makes it a second way to
  // type, and it has no ref -- the field it writes into is whatever happens to
  // be focused. The rail that guards `type` therefore has to be able to ask this
  // question, and it could not: a password could be filled a character at a time
  // with no confirmation, and the characters were written into a recorded macro
  // verbatim. `secret` is the same expression the element table uses, so the
  // field `keys` refuses is the field whose value the table masks.
  //
  // Three answers, because two would collapse cases that need different
  // handling: `{focused: true, ...}` for a field, `{focused: false}` when
  // nothing is focused and the text would go nowhere, and `{unknown: true}` when
  // focus is inside a frame this document cannot read. That last one is not a
  // claim that the field is ordinary. Neither sentinel is `null`, because a
  // `null` from the page and a failed evaluation look the same to the caller.
  const active = () => {
    let e = document.activeElement;
    try {
      for (let hops = 0; e && e.tagName === 'IFRAME' && hops < 10; hops += 1) {
        const inner = e.contentDocument;
        if (!inner) return { unknown: true };
        e = inner.activeElement;
      }
    } catch (_) { return { unknown: true }; }
    if (!e || e === e.ownerDocument.body || e === e.ownerDocument.documentElement) {
      return { focused: false };
    }
    const name = clean(nameOf(e)).slice(0, 120);
    return {
      focused: true,
      name,
      role: roleOf(e) || '',
      secret: isPassword(e) || (SECRET_HINT.test(name) && isEditable(e)),
    };
  };

  // The names of the controls Enter in this field would stand in for.
  //
  // Enter in a text field submits its form as if the form's default button had been clicked
  // (implicit submission), and a page's own Enter handler usually does the same for its dialog. So
  // `type` with `submit` must answer to the rail that guards clicking those buttons, or "Pay now"
  // needs confirming when clicked and not when the Amount field is sent. Reported as names, and the
  // server runs its own confirmation rules over them, so there is one rule list and it lives there.
  // `null` (not `[]`) when the ref is gone: "nothing to confirm" and "could not look" differ.
  // An element and each shadow host it sits inside, innermost first.
  const hostChain = e => {
    const out = [];
    for (let n = e, hops = 0; n && hops < 20; hops += 1) {
      out.push(n);
      const root = n.getRootNode && n.getRootNode();
      n = root instanceof ShadowRoot ? root.host : null;
    }
    return out;
  };
  // Every element under `root`, through open shadow roots.
  const deepAll = (root, out) => {
    out = out || [];
    for (const x of root.querySelectorAll('*')) {
      out.push(x);
      if (x.shadowRoot) deepAll(x.shadowRoot, out);
    }
    return out;
  };
  const PRESSABLE = 'button,input[type="submit"],input[type="image"],input[type="button"],[role="button"]';
  const pressable = x => x.matches && x.matches(PRESSABLE);
  // Anything a click or Enter activates. Links and menu items are here because Enter on a
  // focused one follows it exactly as a click does.
  const ACTIVATABLE = PRESSABLE + ',a[href],[role="link"],[role="menuitem"],[role="menuitemradio"],'
    + '[role="menuitemcheckbox"],[role="tab"],[role="option"],summary';
  const activatable = x => x && x.nodeType === 1 && x.matches && x.matches(ACTIVATABLE);
  // Text drawn by CSS (`.pay::before { content: 'Pay now' }`) is on screen and in no DOM text.
  const drawnText = x => {
    const out = [];
    for (const n of [x, ...x.querySelectorAll('*')].slice(0, 12)) {
      for (const which of ['::before', '::after']) {
        let c = '';
        try { c = getComputedStyle(n, which).content; } catch (_) { c = ''; }
        if (c && c !== 'none' && c !== 'normal') out.push(c.replace(/^["']|["']$/g, ''));
      }
    }
    return out.join(' ');
  };
  // Every name a button goes by. The rail must match on what the user sees as well as the accessible
  // name: `<input type=submit value="Pay now" aria-label="Continue">` says Pay now on screen.
  const pressNames = x => {
    const names = [nameOf(x), x.innerText, rawAttr(x, 'alt'), rawAttr(x, 'title'), drawnText(x)];
    if (FLAT.includes(typeOf(x))) names.push(x.value);
    // A design-system button: the real <button> lives in a shadow root and its text is slotted in.
    const root = x.getRootNode && x.getRootNode();
    if (root instanceof ShadowRoot) names.push(root.host.innerText || root.host.textContent);
    return names.map(n => clean(n).slice(0, 120)).filter(Boolean);
  };
  const liveButtons = scope => deepAll(scope).filter(x => pressable(x) && deepVisible(x) && !disabled(x));
  const parentOf = n => n.parentElement
    || (n.getRootNode && n.getRootNode() instanceof ShadowRoot ? n.getRootNode().host : null);
  // A click on an element is a click on every activatable ancestor it bubbles through: a decoy
  // "Continue" inside the "Pay now" button pays.
  const pressNamesUp = e => {
    const names = pressNames(e);
    for (let n = parentOf(e), hops = 0; n && hops < 16 && n !== document.body; n = parentOf(n), hops += 1) {
      if (activatable(n)) names.push(...pressNames(n));
    }
    return [...new Set(names)];
  };
  // The control implicit submission presses: the form's first submit button, in tree order.
  const isSubmitControl = x => (x.tagName === 'BUTTON' && !['button', 'reset'].includes(typeOf(x)))
    || (x.tagName === 'INPUT' && ['submit', 'image'].includes(typeOf(x)));
  const defaultButton = form => {
    for (const x of form.elements) if (isSubmitControl(x)) return x;
    return null;
  };

  // The names of the controls Enter in this field could stand in for.
  //
  // Enter in a text field submits its form as if its default button had been clicked, and a page's
  // own Enter handler usually presses its dialog's or its wrapper's button. So Enter answers to the
  // rail that guards clicking those buttons. The scope is the union of the field's form and dialog,
  // found through shadow roots; with neither, the nearest ancestor holding a button (a page handler
  // presses what is next to the field). Hidden and disabled controls are skipped: Enter cannot press
  // them. Names only -- the server runs its own confirmation rules over them, one list, in one place.
  // `null` (not `[]`) when the ref is gone: "nothing to confirm" and "could not look" differ.
  const submittersOf = e => {
    if (!e || !e.isConnected) return null;
    const found = new Set();
    for (const n of hostChain(e)) {
      const form = n.form || (n.closest && n.closest('form'));
      if (form) {
        // Implicit submission presses the default button and nothing else. With none, the form
        // submits as a whole, which is as good as pressing any of its buttons.
        const primary = defaultButton(form);
        if (primary) {
          if (!disabled(primary)) found.add(primary);
        } else {
          liveButtons(form).forEach(x => found.add(x));
        }
      }
      // A dialog's own Enter handler can press any button in it.
      const dialog = n.closest && n.closest('dialog,[role="dialog"],[role="alertdialog"]');
      if (dialog) liveButtons(dialog).forEach(x => found.add(x));
    }
    // Everything else a page's Enter handler might press is caught when it happens: see `arm`.
    return [...new Set([...found].flatMap(pressNames))];
  };
  const submitters = ref => submittersOf(nodeFor(ref));
  // A pass-through overlay (see `passThrough`) is clicked where it is drawn, so the click presses
  // whatever of its row lies under its centre: an overlay named "Continue" over a button named
  // "Delete account" deletes the account. Read from geometry, not a hit test, so it holds before
  // `act` has scrolled the ref into view. The tripwire (`arm`) still watches the click itself.
  const underneath = e => {
    const row = passThrough(e);
    if (!row) return [];
    const r = e.getBoundingClientRect();
    const cx = r.x + r.width / 2, cy = r.y + r.height / 2;
    return deepAll(row).filter(x => x !== e && !e.contains(x) && activatable(x) && (() => {
      const b = x.getBoundingClientRect();
      return cx >= b.left && cx <= b.right && cy >= b.top && cy <= b.bottom;
    })());
  };
  // Every name one control goes by (accessible name, visible text, value, alt), for the click rail.
  const pressNamesOf = ref => {
    const e = nodeFor(ref);
    if (!e || !e.isConnected) return null;
    return [...new Set([...pressNamesUp(e), ...underneath(e).flatMap(pressNamesUp)])];
  };
  // Whether `type` may write into this ref. Clicking is what `type` does first, so a `type` aimed at
  // a button is a click that the click rail never saw.
  const editable = ref => {
    const e = nodeFor(ref);
    return !!(e && e.isConnected && (isEditable(e) || e.isContentEditable));
  };

  // What pressing Enter or Space *now* would press: the focused button itself, or whatever the
  // focused field submits. For `keys`, which has no ref and presses into whatever has focus.
  // `null` when focus sits somewhere this document cannot read.
  const pressTargets = () => {
    let e = document.activeElement;
    try {
      for (let hops = 0; e && hops < 20; hops += 1) {
        if (e.tagName === 'IFRAME') { if (!e.contentDocument) return null; e = e.contentDocument.activeElement; continue; }
        if (e.shadowRoot && e.shadowRoot.activeElement) { e = e.shadowRoot.activeElement; continue; }
        break;
      }
    } catch (_) { return null; }
    if (!e || e === e.ownerDocument.body || e === e.ownerDocument.documentElement) return [];
    const field = isEditable(e) || e.isContentEditable || e.tagName === 'TEXTAREA';
    return field ? submittersOf(e) : pressNamesUp(e);
  };

  // The tripwire. Where a key press or a click *leads* cannot be read off the layout: a page's own
  // handler can press a button anywhere. So while an unconfirmed input is dispatched, any click or
  // form submission that would activate a control matching a confirmation rule is cancelled before
  // the page sees it, and reported. Capture phase on the window, so it runs before every handler
  // below it; cancelling a click also cancels the submission it would have started.
  const INVISIBLE = /[\u200b\u200c\u200d\u2060\ufeff\u00ad]/g;
  const normalName = s => String(s || '').normalize('NFKC').replace(INVISIBLE, '').toLowerCase();
  const TRIP = { rules: null, hits: [] };
  const tripNames = ev => {
    if (ev.type === 'submit') {
      const form = ev.target;
      if (ev.submitter) return pressNamesUp(ev.submitter);
      return form && form.tagName === 'FORM' ? liveButtons(form).flatMap(pressNames) : [];
    }
    const names = [];
    for (const n of (ev.composedPath ? ev.composedPath() : [ev.target])) {
      if (activatable(n)) names.push(...pressNames(n));
    }
    return names;
  };
  const tripCheck = ev => {
    if (!TRIP.rules) return;
    let hit = null;
    try { hit = tripNames(ev).find(n => TRIP.rules.some(rule => rule.test(normalName(n)))); } catch (_) { hit = null; }
    if (hit) {
      ev.preventDefault();
      ev.stopImmediatePropagation();
      TRIP.hits.push(clean(hit).slice(0, 120));
    }
  };
  W.addEventListener('click', tripCheck, true);
  W.addEventListener('submit', tripCheck, true);
  const arm = patterns => {
    TRIP.rules = patterns.map(p => new RegExp(p, 'i'));
    TRIP.hits = [];
    return true;
  };
  const disarm = () => { const hits = TRIP.hits; TRIP.rules = null; TRIP.hits = []; return hits; };

  const stats = () => ({ refs: S.nodes.size, next: S.next, hasSnap: !!S.snap });

  W.__jevMcp = {
    version: VERSION, readState, verify, reinspect, resolve, scrollTo, selectOption,
    settle, label, active, submitters, pressTargets, pressNamesOf, editable, arm, disarm, stats,
    keyOf, guardOf,
  };
})();
