/* The element table, rendered the way the server renders it.
 *
 * This is a port of `jev_ultrafast_mcp/observe.py` — `ROLE_CODE`, `_short`,
 * `Element.render` and `Observation.render` — so that what the extension shows is
 * byte-for-byte what `jev-ultrafast-mcp` would hand a model for the same page.
 * The point of the extension is to be a window onto that, not a second opinion
 * about it, so the two must not drift.
 *
 * Two details are deliberately Python-shaped rather than JavaScript-shaped,
 * because matching the server matters more than matching the language:
 *
 *   - lengths are counted in code points, not UTF-16 units, so a label ending in
 *     an emoji truncates at the same character Python would truncate at;
 *   - `scroll.get(key, 0)` is reproduced with an own-property check, so a present
 *     key is never replaced by the default.
 *
 * Parity is enforced by `test/render-parity.mjs` against fixtures generated by the
 * real Python renderer, and by `tests/test_extension.py`.
 */

export const ROLE_CODE = {
  button: 'btn', link: 'lnk', textbox: 'inp', searchbox: 'srch',
  combobox: 'cmb', checkbox: 'chk', radio: 'rad', switch: 'sw',
  tab: 'tab', menuitem: 'mi', menuitemcheckbox: 'mic', menuitemradio: 'mir',
  option: 'opt', treeitem: 'tree', gridcell: 'cell', spinbutton: 'spin',
  listbox: 'list', file: 'file',
};

/* Mirrors `config.DEFAULT_SECRET_PATTERNS`. The observer marks some fields itself;
 * these are the ones the server additionally refuses to echo, and the extension
 * has the same obligation — it is showing a value to a human, but it is also
 * showing exactly what the server would have sent. */
export const DEFAULT_SECRET_PATTERNS = [
  '\\bpass(word|wd|code|phrase)\\b', '\\bpassphrase\\b', '\\botp\\b',
  '\\bone[- ]?time\\b', '\\bverification code\\b', '\\bsecurity code\\b',
  '\\bcvv\\b', '\\bcvc\\b', '\\bcard\\s*number\\b', '\\bsecret\\b',
  '\\bapi\\s*key\\b', '\\baccess\\s*token\\b', '\\bssn\\b', '\\bsocial security\\b',
  '\\biban\\b', '\\brouting\\s*number\\b', '\\bsecurity\\s*answer\\b', '\\bpin\\b',
];

const ELLIPSIS = '\u2026';
const FLAG_COVERED = '\u2298';
const FLAG_OFFSCREEN = '\u00bb';
const FLAG_DISABLED = '\u2297';
const FLAG_HOVER = '\u22ee';
const FLAG_EXPANDED = '\u25be';
const FLAG_CHECKED = '\u2713';
const FLAG_UNCHECKED = '\u00b7';
const ARROW = '\u25b8';
const HIDDEN = '\u00abhidden\u00bb';

/** Code points, so `short()` cuts where Python's `str` slicing cuts. */
export function codePoints(text) {
  return Array.from(String(text ?? ''));
}

/** Python's `f"{value:<width}"` — left-justify, never truncate. */
export function padRight(text, width) {
  const value = String(text ?? '');
  const missing = width - codePoints(value).length;
  return missing > 0 ? value + ' '.repeat(missing) : value;
}

/** Python's `_short`: collapse whitespace, then truncate on a code-point boundary. */
export function short(text, limit) {
  const collapsed = String(text ?? '').split(/\s+/).filter(Boolean).join(' ');
  const chars = codePoints(collapsed);
  if (chars.length <= limit) return collapsed;
  return chars.slice(0, limit - 1).join('') + ELLIPSIS;
}

/** Python's `safety.is_secret`, minus the Config plumbing. */
export function isSecret(name, role, patterns = DEFAULT_SECRET_PATTERNS) {
  if (role && String(role).toLowerCase() === 'password') return true;
  const haystack = String(name || '').toLowerCase();
  return patterns.some((pattern) => new RegExp(pattern, 'i').test(haystack));
}

/** Python's `Element.from_raw`, including the truncations applied at construction. */
export function elementFromRaw(raw, { secret = false } = {}) {
  return {
    ref: raw.ref,
    role: raw.role || 'generic',
    name: short(raw.name || '', 160),
    value: short(raw.value || '', 160),
    editable: Boolean(raw.editable),
    occluded: Boolean(raw.occluded),
    checked: raw.checked === undefined ? null : raw.checked,
    current: raw.current ? short(raw.current, 120) : null,
    expanded: raw.expanded === undefined ? null : raw.expanded,
    options: raw.options || [],
    opts_total: raw.opts_total || 0,
    secret: Boolean(raw.secret) || secret,
    context: short(raw.context || '', 100),
    accept: raw.accept === undefined ? null : raw.accept,
    multiple: Boolean(raw.multiple),
    label: short(raw.label || '', 160),
    hoverable: Boolean(raw.hoverable),
    multiline: Boolean(raw.multiline),
    disabled: Boolean(raw.disabled),
    in_viewport: raw.inViewport === undefined ? true : Boolean(raw.inViewport),
  };
}

/** The role code shown in the table's second column. */
export function roleCode(role) {
  return ROLE_CODE[role] || String(role || '').slice(0, 4);
}

/** Python's `Element.signature` — what is worth telling the agent about. */
export function elementSignature(element) {
  return [
    element.role, element.name, element.value, element.checked, element.current,
    element.expanded, element.occluded, element.editable, element.disabled,
  ];
}

/** Python's `Element.render`, character for character. */
export function elementRender(element, { detail = false, mask = true } = {}) {
  let flags = '';
  if (element.editable) flags += '*';
  if (element.occluded) flags += FLAG_COVERED;
  else if (!element.in_viewport) flags += FLAG_OFFSCREEN;
  if (element.disabled) flags += FLAG_DISABLED;
  if (element.hoverable && element.expanded !== 'true') flags += FLAG_HOVER;
  if (element.expanded === 'true') flags += FLAG_EXPANDED;
  if (element.checked === true) flags += FLAG_CHECKED;
  else if (element.checked === false) flags += FLAG_UNCHECKED;

  const head = padRight(element.ref, 5) + roleCode(element.role) + padRight(flags, 3);
  let body = element.name || element.label || `<${element.role}>`;

  if (element.role === 'file') {
    body = `${body} accept=${element.accept || '*'}` + (element.multiple ? ' [multiple]' : '');
  } else if ((element.role === 'combobox' || element.role === 'listbox') && element.options.length) {
    const shown = element.options.slice(0, detail ? 20 : 8);
    const rendered = shown.map((option) => {
      const label = short(option.label || '', 24);
      const value = option.value;
      const plain = value === null || value === undefined || value === '' || value === label;
      return plain ? label : `${label}=${short(String(value), 18)}`;
    });
    const total = Number(element.opts_total) || 0;
    const more = total <= shown.length ? '' : ` +${total - shown.length}`;
    const current = element.current || '(none)';
    body = `${body} ${ARROW} ${current} opts{${rendered.join(' | ')}${more}}`;
  } else if (element.editable) {
    let value = element.value || '';
    if (element.secret && mask) value = value ? HIDDEN : '';
    body = `${body} ${ARROW} "${value}"`;
  } else if (element.value) {
    body = `${body} ${ARROW} "${element.value}"`;
  }

  if (element.context && !detail) body += `  @${element.context}`;
  return `${head} ${body}`;
}

/** Python's `Observation.from_raw`. */
export function observationFromRaw(raw, { maskSecrets = null, sequence = 0 } = {}) {
  const elements = (raw.actions || []).map((item) => {
    let secret = Boolean(item.secret);
    if (maskSecrets) secret = secret || Boolean(maskSecrets(item.name || '', item.role || ''));
    return elementFromRaw(item, { secret });
  });
  const text = raw.text || '';
  return {
    url: raw.url || '',
    title: short(raw.title || '', 120),
    text,
    elements,
    text_digest: text, // the renderer only compares it, so the text itself will do
    page_key: raw.page_key || '',
    scroll: raw.scroll || {},
    reachable: Number(raw.reachable) || 0,
    omitted: Number(raw.omitted) || 0,
    overlays: raw.overlays || [],
    cross_frames: Number(raw.cross_frames) || 0,
    cross_frame_srcs: raw.cross_frame_srcs || [],
    offscreen: Number(raw.offscreen) || 0,
    sequence,
    // `new_tabs` and `tabs` are deliberately *not* read from `raw`: the observer never emits them.
    // The browser layer sets `new_tabs` after construction (`browser.py` diffs the tab list against
    // the ones it already knew about), which is the only place that can see tabs at all. These are
    // the dataclass defaults, so a raw payload carrying the keys changes nothing.
    new_tabs: [],
    tabs: [],
  };
}

/** Python's `dict.get(key, default)` — a present key is never replaced. */
function scrollValue(scroll, key) {
  return Object.prototype.hasOwnProperty.call(scroll, key) ? scroll[key] : 0;
}

function warningsFor(observation) {
  const warnings = [];
  for (const overlay of observation.overlays) {
    warnings.push(`dialog open: ${overlay.name || overlay.role}`
      + (overlay.modal ? ' [modal]' : ''));
  }
  if (observation.cross_frames) {
    const sample = observation.cross_frame_srcs.slice(0, 2).join(', ');
    warnings.push(`${observation.cross_frames} cross-origin frame(s) not readable`
      + (sample ? ` (${sample})` : ''));
  }
  for (const tab of observation.new_tabs) {
    warnings.push(`NEW TAB opened: ${tab.url} \u2192 switch with `
      + `{'op':'tab','action':'switch','target_id':'${tab.target_id}'}`);
  }
  return warnings;
}

function deltaLines(observation, previous, detailRefs) {
  const before = new Map(previous.elements.map((element) => [element.ref, element]));
  const after = new Map(observation.elements.map((element) => [element.ref, element]));

  const changed = [];
  const added = [];
  for (const [ref, element] of after) {
    if (!before.has(ref)) added.push(element);
    else if (elementSignature(before.get(ref)).join('\u0000')
             !== elementSignature(element).join('\u0000')) changed.push(element);
  }
  const gone = [...before.keys()].filter((ref) => !after.has(ref));

  if (!changed.length && !added.length && !gone.length) {
    return [`  = no change (${after.size} elements)`];
  }

  const lines = [];
  for (const element of added) {
    lines.push(`+ ${elementRender(element, { detail: detailRefs.has(element.ref) })}`);
  }
  for (const element of changed) {
    const old = before.get(element.ref);
    let note = '';
    if (old.value !== element.value && element.editable) note = `   (was "${old.value}")`;
    else if (old.occluded !== element.occluded) {
      note = element.occluded ? '   (now covered)' : '   (now reachable)';
    } else if (old.disabled !== element.disabled) {
      note = element.disabled ? '   (now disabled)' : '   (now usable)';
    }
    lines.push(`~ ${elementRender(element, { detail: detailRefs.has(element.ref) })}${note}`);
  }
  for (const ref of gone) lines.push(`- ${ref}  (removed)`);
  lines.push(`  ${changed.length} changed, ${added.length} new, ${gone.length} gone`);
  return lines;
}

/**
 * Python's `Observation.render`, as a list of lines.
 *
 * `mode` is `auto` (delta when a previous observation of the same page is
 * supplied), `full` (every element, in detail) or `delta`.
 */
export function observationLines(observation, {
  previous = null, mode = 'auto', includeText = true, focus = null, maxText = 4000,
} = {}) {
  let useDelta = mode === 'delta'
    || (mode === 'auto' && previous !== null && previous.url === observation.url);
  if (useDelta && previous === null) useDelta = false;

  const marker = useDelta ? 'delta' : 'obs';
  let header = `[${marker}#${observation.sequence}] ${observation.url}  "${observation.title}"  `
    + `scroll=${scrollValue(observation.scroll, 'y')}/${scrollValue(observation.scroll, 'height')}  `
    + `reachable=${observation.reachable}/${observation.elements.length}`;
  if (observation.omitted) header += `  (omitted ${observation.omitted} low-priority)`;
  if (observation.offscreen) {
    header += `  (offscreen ${observation.offscreen}, ${FLAG_OFFSCREEN} = will scroll on act)`;
  }
  const triggers = observation.elements.filter(
    element => element.hoverable && element.expanded !== 'true',
  ).length;
  if (triggers) {
    header += `  (${triggers} ${FLAG_HOVER} = menu trigger, hover before choosing)`;
  }

  const lines = [header];
  for (const warning of warningsFor(observation)) lines.push(`  ! ${warning}`);

  const detailRefs = new Set(focus || []);
  if (useDelta) {
    lines.push(...deltaLines(observation, previous, detailRefs));
  } else {
    for (const element of observation.elements) {
      lines.push(elementRender(element, {
        detail: detailRefs.has(element.ref) || mode === 'full',
      }));
    }
    if (!observation.elements.length) lines.push('  (no actionable elements visible)');
  }

  if (includeText && observation.text) {
    const fresh = previous === null || observation.text_digest !== previous.text_digest;
    if (fresh) {
      lines.push('text:');
      lines.push(short(observation.text, maxText));
    }
  }
  return lines;
}

/** The same thing as one string, which is what the server sends. */
export function renderObservation(observation, options = {}) {
  return observationLines(observation, options).join('\n');
}
